name: Apply Terraform plan in AWS

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          variables: |
            access_key = "${{ secrets.TERRAFORM_ACCESS_KEY }}"
            secret_key = "${{ secrets.TERRAFORM_SECRET_KEY }}"
            token_key = "${{ secrets.TERRAFORM_TOKEN_KEY }}"
            role_arn = "${{ secrets.TERRAFORM_ROLE_ARN }}"
