name: My Target Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN :
        required: true
      AWS_REGION:
        required: true

env:
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_token_key: ${{ secrets.AWS_SESSION_TOKEN }} | base64 --decode
  TF_VAR_aws_region: ${{ secrets.AWS_REGION }}

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: "ASIAZ3PR22SGMKU5C3S7"
          aws-secret-access-key: "IhCY8lBwG65jDzZWdGxQd9gZWo0V8P6FvloXxSjC"
          aws-session-token: "IQoJb3JpZ2luX2VjENP//////////wEaCXVzLXdlc3QtMiJHMEUCIQDu0eee2v+eZkIVLd3/VG907qUuamT+gL706s/eRm2C2gIgTelePbgYczofwySa9docEQDxvZ7bGyQdU/3ltZEeTzEqqgIILBACGgw2Nzc1MDEzOTIwMTIiDMsH/JxNvNabzrW3VSqHAu4IiiiEr03nJ0qk63Okz2vzMDUiMIpJCkhNX7NUZ+TmeXyE7ORn/CMZM8rvqmZ5y+sT1YONMghqdoq5lSmDOZCvCh/JEvHLOM11oV4jN7C6jDhu8i7/6eOKsiHjnK/FdGG6RqgkXG9pwCfWkjdB+SCZyVfttUTXQXtQ+mukUSLbrl+t5aFns8ajyOw5rHP3g0Z6eM+RK52JBucGR54HXm8y4QQxw+qE9G9zSyMB4nMtsDXQfuvZdADWJjlF7wD3L/+CgLJ0mlG43lMUt9UO4Zm9lG1lRNg2OTzx09VgzbqWbReoLF8IuysIYS48nxe14MR7zlVIWMXxSsW/pxbnThht3aaRn8XmMOfg2r4GOp0BKSbK7iZ2fJGTitce/8JLvXHuOcLhButKOjI2mXLvWwNdL36Wd90hxvkx+vQKtSKof6tjY0mJHQXl3ZlOp4HqX454ZObo1KUZrLIk/P2zAwtadp1fx4SB/RO1TkxHrukw3kJD8Wk9Vgzyu2GdaVm3MuM6KD/4rYqddvReedvacNEJCi2qhXvav2TQryCsm4D/rBUGeyjIzE8GF9Ol2Q=="
          aws-region: "us-east-1"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fiap-9soat/fiap-lanchonete-auth
          token: ${{ secrets.PAT }}
          clean: false
      
      - name: terraform apply
        uses: dflook/terraform-apply@v1


