name: My Target Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN :
        required: true
      AWS_REGION:
        required: true
      GITHUB_TOKEN:
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} | base64 --decode
  AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          variables: |
            access_key = $AWS_ACCESS_KEY_ID
            secret_key = $AWS_SECRET_ACCESS_KEY
            token_key = $AWS_SESSION_TOKEN
