name: My Target Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN :
        required: true
      AWS_REGION:
        required: true

env:
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # TF_VAR_aws_token_key: ${{ secrets.AWS_SESSION_TOKEN }} | base64 --decode
  TF_VAR_aws_token_key: ${{ secrets.AWS_SESSION_TOKEN }}
  TF_VAR_aws_region: ${{ secrets.AWS_REGION }}

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} | base64 --decode
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fiap-9soat/fiap-lanchonete-auth
          token: ${{ secrets.PAT }}
          clean: false
      
      - name: terraform apply
        uses: dflook/terraform-apply@v1


